---
title: "penguin_filtering"
author: "Marie Rivers"
date: "8/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

```{r}
View(penguins)
```

I want to create a scatterplot of flipper length vs body mass, with body mass converted to kilograms, only for Adelie penguins.

```{r}
# use filter to create subset of data. Use pipe operator to perform things in sequence (and then), pipe shortcut = command + shift + M
adelies <- penguins %>% # start with penguins then do this... Use two equal signs because you are asking "is equal?"
  filter(species == "Adelie") %>%  #dont need to write the data frame because you already piped it in
  mutate(body_mass_kg = body_mass_g / 1000) # used one equal sign because we are assigning, not asking if equal
unique(adelies$species)

ggplot(data = adelies, aes(x = flipper_length_mm, y = body_mass_kg)) +
  geom_point(aes(color = island)) +
  facet_wrap(~island)
```
```{r}
ggplot(data = adelies, aes(x = flipper_length_mm, y = body_mass_kg)) +
  geom_point(color = "blue") +
  geom_line(aes(color = island)) +
  facet_wrap(~island)
```

